import express, { type NextFunction, type Request, type Response } from "express";
import cookieParser from "cookie-parser";
import { randomUUID } from "node:crypto";
import { config } from "./config.js";
import { createOAuthState, verifyOAuthState } from "./auth/oauth.js";
import { attackTraceSchema, historySchema, ingestSchema } from "./types.js";
import type { Repository } from "./db/repository.js";

type AuthenticatedRequest = Request & { user?: { id: string; github_id: string; username: string; avatar_url?: string } };
const jsonError = (res: Response, status: number, code: string, message: string) => res.status(status).json({ error: { code, message } });

export function createApp(repository: Repository) {
  const app = express(); app.disable("x-powered-by"); app.use(cookieParser()); app.use(express.json({ limit: "2mb" }));
  app.get("/health", (_req, res) => res.json({ status: "ok", service: "visualizer-api" }));
  app.post("/api/v1/analyses/ingest", async (req, res, next) => { try { if (req.header("authorization") !== `Bearer ${config.INGEST_TOKEN}`) return jsonError(res, 401, "UNAUTHORIZED", "ingest token required"); const parsed = ingestSchema.safeParse(req.body); if (!parsed.success) return jsonError(res, 400, "INVALID_ANALYSIS", "analysis payload does not match the contract"); const detail = await repository.ingest(parsed.data); return res.status(201).json({ data: detail }); } catch (error) { next(error); } });
  app.get("/api/v1/analyses", async (req, res, next) => { try { const limit = Math.min(Math.max(Number(req.query.limit ?? 25), 1), 100); const offset = Math.max(Number(req.query.offset ?? 0), 0); return res.json({ data: await repository.listAnalyses(limit, offset) }); } catch (error) { next(error); } });
  app.get("/api/v1/analyses/:id", async (req, res, next) => { try { const detail = await repository.getAnalysis(req.params.id); return detail ? res.json({ data: detail }) : jsonError(res, 404, "NOT_FOUND", "analysis not found"); } catch (error) { next(error); } });
  app.get("/api/v1/analyses/:id/graph", async (req, res, next) => { try { const detail = await repository.getAnalysis(req.params.id); if (!detail) return jsonError(res, 404, "NOT_FOUND", "analysis not found"); const nodes = detail.events.map((event: any) => ({ id: event.event_id, type: event.event_type, sequence: event.sequence, timestamp: event.timestamp ?? event.event_timestamp })); return res.json({ data: { analysis_id: detail.id, nodes, edges: [] } }); } catch (error) { next(error); } });
  app.use("/api/v1", async (req: AuthenticatedRequest, _res, next) => { const token = req.header("authorization")?.replace(/^Bearer\s+/i, ""); if (token) req.user = (await repository.findSession(token)) ?? undefined; next(); });
  app.post("/api/v1/visualization-history", async (req: AuthenticatedRequest, res, next) => { try { if (!req.user) return jsonError(res, 401, "UNAUTHORIZED", "login required"); const parsed = historySchema.safeParse(req.body); if (!parsed.success) return jsonError(res, 400, "INVALID_HISTORY", "invalid visualization history"); await repository.recordHistory(req.user.id, parsed.data); return res.status(201).json({ data: { recorded: true } }); } catch (error) { next(error); } });
  app.get("/api/auth/github/redirect", (req, res) => { if (!config.GITHUB_CLIENT_ID) return jsonError(res, 503, "OAUTH_NOT_CONFIGURED", "GitHub OAuth is not configured"); const state = createOAuthState(typeof req.query.returnTo === "string" ? req.query.returnTo : undefined); res.cookie("honeytrace_oauth_state", state, { httpOnly: true, sameSite: "lax", secure: process.env.NODE_ENV === "production", maxAge: 10 * 60 * 1000 }); const params = new URLSearchParams({ client_id: config.GITHUB_CLIENT_ID, redirect_uri: config.GITHUB_CALLBACK_URL, scope: "read:user user:email", state }); res.redirect(`https://github.com/login/oauth/authorize?${params}`); });
  app.get("/api/auth/github/callback", async (req, res, next) => { try { const state = typeof req.query.state === "string" ? req.query.state : ""; const expected = req.cookies.honeytrace_oauth_state as string | undefined; verifyOAuthState(state, expected ?? ""); res.clearCookie("honeytrace_oauth_state"); if (!config.GITHUB_CLIENT_SECRET) return jsonError(res, 503, "OAUTH_NOT_CONFIGURED", "GitHub OAuth is not configured"); const tokenResponse = await fetch("https://github.com/login/oauth/access_token", { method: "POST", headers: { accept: "application/json", "content-type": "application/json" }, body: JSON.stringify({ client_id: config.GITHUB_CLIENT_ID, client_secret: config.GITHUB_CLIENT_SECRET, code: req.query.code }) }); const token = await tokenResponse.json() as { access_token?: string }; if (!token.access_token) return jsonError(res, 401, "OAUTH_FAILED", "GitHub token exchange failed"); const profileResponse = await fetch("https://api.github.com/user", { headers: { authorization: `Bearer ${token.access_token}`, accept: "application/vnd.github+json", "user-agent": "honeytrace-visualizer" } }); if (!profileResponse.ok) return jsonError(res, 401, "OAUTH_FAILED", "GitHub profile lookup failed"); const profile = await profileResponse.json() as { id: number; login: string; avatar_url?: string }; const session = await repository.createOAuthSession(String(profile.id), profile.login, profile.avatar_url); return res.redirect(`${config.FRONTEND_URL}/auth/callback#access_token=${encodeURIComponent(session)}`); } catch (error) { next(error); } });
  app.post("/api/auth/logout", async (req, res, next) => { try { const token = req.header("authorization")?.replace(/^Bearer\s+/i, ""); if (token) await repository.revokeSession(token); return res.status(204).send(); } catch (error) { next(error); } });
  app.use((error: unknown, _req: Request, res: Response, _next: NextFunction) => { console.error(error); return jsonError(res, 500, "INTERNAL_ERROR", "internal server error"); });
  return app;
}
