import { FormEvent, useState } from "react";
import { useMutation, useQuery, useQueryClient } from "@tanstack/react-query";
import { Copy, KeyRound, Plus, Trash2 } from "lucide-react";
import { api } from "../lib/api";
import { formatDate } from "../lib/format";
import { EmptyState, ErrorState, LoadingState } from "../components/States";

export function Devices() {
  const client = useQueryClient(); const [name, setName] = useState(""); const [revealed, setRevealed] = useState<string | null>(null); const tokens = useQuery({ queryKey: ["tokens"], queryFn: api.tokens });
  const create = useMutation({ mutationFn: api.createToken, onSuccess: (token) => { setRevealed(token.token ?? null); setName(""); void client.invalidateQueries({ queryKey: ["tokens"] }); } });
  const revoke = useMutation({ mutationFn: api.revokeToken, onSuccess: () => void client.invalidateQueries({ queryKey: ["tokens"] }) });
  const submit = (event: FormEvent) => { event.preventDefault(); if (name.trim()) create.mutate(name.trim()); };
  return <div className="page"><div className="page-heading"><div><h1 className="page-title font-display">Dispositivos</h1><p className="page-subtitle">Tokens para asociar el Engine o una Raspberry Pi con tu cuenta.</p></div></div>
    <section className="card mb-4"><div className="section-header"><div><h2 className="section-title">Nuevo token de ingestión</h2><p className="mt-1 text-sm text-[var(--text-tertiary)]">El valor completo se muestra una sola vez.</p></div></div><form className="flex flex-wrap items-end gap-3 p-5" onSubmit={submit}><label className="min-w-64 flex-1 text-sm text-[var(--text-tertiary)]">Nombre del dispositivo<input className="input mt-2" value={name} onChange={(event) => setName(event.target.value)} placeholder="Raspberry laboratorio" maxLength={80} /></label><button className="button-primary" disabled={!name.trim() || create.isPending}><Plus size={16} />Crear token</button></form>{revealed && <div className="token-reveal m-5 mt-0"><div className="mb-2 flex items-center gap-2 font-medium"><KeyRound size={16} />Guárdalo ahora</div><div className="flex items-center gap-2"><code className="font-mono min-w-0 flex-1 overflow-x-auto text-sm">{revealed}</code><button className="button-secondary min-w-8" onClick={() => void navigator.clipboard.writeText(revealed)} aria-label="Copiar token"><Copy size={16} /></button></div></div>}</section>
    <section className="card"><div className="section-header"><h2 className="section-title">Tokens configurados</h2></div>{tokens.isLoading ? <LoadingState /> : tokens.isError ? <ErrorState retry={() => void tokens.refetch()} /> : !tokens.data?.length ? <EmptyState title="No hay dispositivos" detail="Crea un token para conectar tu primera fuente." /> : <div className="table-wrap"><table className="data-table"><thead><tr><th>Nombre</th><th>Identificador</th><th>Creado</th><th>Último uso</th><th><span className="sr-only">Acciones</span></th></tr></thead><tbody>{tokens.data.map((token) => <tr key={token.id}><td className="text-[var(--text-primary)]">{token.name}</td><td className="font-mono">••••••••{token.token_hint}</td><td className="font-mono">{formatDate(token.created_at)}</td><td className="font-mono">{token.last_used_at ? formatDate(token.last_used_at) : "Sin uso"}</td><td><button className="button-ghost button-danger min-h-8 min-w-8" onClick={() => { if (confirm(`¿Revocar el token “${token.name}”?`)) revoke.mutate(token.id); }} aria-label={`Revocar ${token.name}`}><Trash2 size={16} /></button></td></tr>)}</tbody></table></div>}</section>
  </div>;
}
