import { useEffect, useMemo, useState } from "react";
import { useQuery } from "@tanstack/react-query";
import { ArrowLeft, Download, FileJson, GitBranch, Lightbulb, Network, ShieldAlert } from "lucide-react";
import { Link, useParams } from "react-router-dom";
import { AttackGraph } from "../components/AttackGraph";
import { ErrorState, LoadingState } from "../components/States";
import { SeverityBadge } from "../components/SeverityBadge";
import { api } from "../lib/api";
import { analysisClassifications, duration, eventLabel, eventSeverity, formatDate } from "../lib/format";
import type { NormalizedEvent } from "../types";

export function Explorer() {
  const { id = "" } = useParams(); const detail = useQuery({ queryKey: ["analysis", id], queryFn: () => api.analysis(id), enabled: Boolean(id) }); const graph = useQuery({ queryKey: ["graph", id], queryFn: () => api.graph(id), enabled: Boolean(id) }); const [selected, setSelected] = useState<string>(); const [hovered, setHovered] = useState<string>();
  useEffect(() => { if (detail.data) { setSelected((value) => value ?? detail.data.events[0]?.event_id); void api.record(id, "opened").catch(() => undefined); } }, [detail.data, id]);
  const activeEvent = useMemo(() => detail.data?.events.find((event) => event.event_id === (hovered ?? selected)), [detail.data, hovered, selected]);
  if (detail.isLoading || graph.isLoading) return <div className="page"><LoadingState label="Cargando reconstrucción…" /></div>;
  if (detail.isError || graph.isError || !detail.data || !graph.data) return <div className="page"><ErrorState retry={() => { void detail.refetch(); void graph.refetch(); }} /></div>;
  const classifications = analysisClassifications(detail.data);
  const interpretation = detail.data.interpretation;
  const exportAnalysis = (format: "json" | "ndjson") => { void api.record(id, "exported", { format }).catch(() => undefined); window.location.assign(api.exportUrl(id, format)); };
  return <div className="page"><div className="page-heading"><div><Link to="/analyses" className="mb-3 inline-flex items-center gap-2 text-sm text-[var(--text-tertiary)] no-underline hover:text-[var(--text-primary)]"><ArrowLeft size={15} />Volver al historial</Link><div className="flex flex-wrap items-center gap-3"><h1 className="page-title font-display">Attack Explorer</h1>{classifications.map((classification) => <SeverityBadge key={classification} severity={classification} />)}</div><p className="page-subtitle font-mono">{detail.data.trace_id}</p></div><div className="flex flex-wrap gap-2"><button className="button-secondary" onClick={() => exportAnalysis("json")}><FileJson size={16} />JSON</button><button className="button-secondary" onClick={() => exportAnalysis("ndjson")}><Download size={16} />NDJSON</button></div></div>
    <section className="metric-grid" aria-label="Resumen del análisis"><Metric label="Confianza" value={`${Math.round(detail.data.confidence * 100)}%`} /><Metric label="Eventos" value={String(detail.data.events.length)} /><Metric label="Duración" value={duration(detail.data.started_at, detail.data.ended_at)} /><Metric label="Técnicas" value={String(detail.data.techniques.length)} /></section>
    {interpretation ? <section className="analysis-report" aria-labelledby="analysis-title"><div className="analysis-report-lead"><Lightbulb size={20} /><div><h2 id="analysis-title">Qué ocurrió</h2><p>{interpretation.overview}</p></div></div><div className="finding-list">{interpretation.findings.map((finding) => <article className="finding-row" key={finding.stage}><div><div className="flex flex-wrap items-center gap-2"><h3>{finding.title}</h3>{finding.technique && <code>{finding.technique}</code>}</div><p>{finding.explanation}</p></div><button className="button-secondary" disabled={!finding.evidence_event_ids[0]} onClick={() => setSelected(finding.evidence_event_ids[0])}>Ver evidencia · {finding.evidence_event_ids.length}</button></article>)}</div><div className="analysis-notes"><p><GitBranch size={16} />{interpretation.graph_explanation}</p><p><ShieldAlert size={16} />{interpretation.confidence_explanation} {interpretation.limitation}</p></div></section> : <section className="analysis-report" aria-labelledby="analysis-title"><div className="analysis-report-lead"><ShieldAlert size={20} /><div><h2 id="analysis-title">Interpretación no disponible</h2><p>La API entregó una versión anterior del análisis. Los eventos continúan disponibles debajo.</p></div></div></section>}
    <section className="card overflow-hidden" aria-labelledby="graph-title"><div className="section-header"><div><div className="flex items-center gap-2"><Network size={17} className="text-[var(--accent)]" /><h2 id="graph-title" className="section-title">Secuencia observada</h2></div><p className="mt-1 text-sm text-[var(--text-tertiary)]">Selecciona un nodo para entender su aporte a la reconstrucción.</p></div><span className="font-mono text-[var(--text-xs)] text-[var(--text-muted)]">{detail.data.source_id}</span></div><div className="explorer-grid"><AttackGraph graph={graph.data} confidence={detail.data.confidence} selectedId={selected} onSelect={setSelected} onHover={setHovered} /><EventDetail event={activeEvent} explanation={activeEvent ? interpretation?.event_explanations[activeEvent.event_id] : undefined} confidence={detail.data.confidence} /></div><div className="timeline" aria-label="Timeline de eventos">{detail.data.events.map((event) => <button key={event.event_id} className={`timeline-node severity-${eventSeverity(event)}`} data-active={(hovered ?? selected) === event.event_id} onMouseEnter={() => setHovered(event.event_id)} onMouseLeave={() => setHovered(undefined)} onClick={() => setSelected(event.event_id)}><span className="timeline-dot" /><span className="font-mono">{String(event.sequence).padStart(2, "0")}</span><span className="mt-1 block text-[var(--text-secondary)]">{eventLabel(event.event_type)}</span></button>)}</div></section>
    <section className="card event-table"><div className="section-header"><h2 className="section-title">Evidencias</h2><span className="text-[var(--text-xs)] text-[var(--text-muted)]">{detail.data.evidence.length} registradas</span></div><div className="table-wrap"><table className="data-table"><thead><tr><th>Evento</th><th>Motivo</th><th>Fuente</th></tr></thead><tbody>{detail.data.evidence.map((evidence) => <tr key={`${evidence.event_id}-${evidence.reason}`}><td><button className="button-ghost font-mono" onClick={() => setSelected(evidence.event_id)}>{evidence.event_id}</button></td><td>{evidence.reason}</td><td className="font-mono">{evidence.source ?? "—"}</td></tr>)}</tbody></table></div></section>
  </div>;
}
function Metric({ label, value }: { label: string; value: string }) { return <article className="metric card"><p className="metric-label">{label}</p><p className="metric-value">{value}</p></article>; }
function EventDetail({ event, explanation, confidence }: { event?: NormalizedEvent; explanation?: string; confidence: number }) { if (!event) return <aside className="detail-panel"><p className="text-sm text-[var(--text-tertiary)]">Selecciona un evento para inspeccionarlo.</p></aside>; const rows = [["IP origen", event.source_ip], ["Timestamp", formatDate(event.timestamp)], ["Endpoint", event.path], ["Método", event.method], ["Estado HTTP", event.status_code], ["Sesión", event.session_id], ["User-Agent", event.user_agent], ["Fuente", event.raw_source], ["Confianza", `${Math.round(confidence * 100)}%`]]; return <aside className="detail-panel" aria-live="polite"><div className="flex flex-wrap items-center gap-2"><h3 className="text-[var(--text-lg)] font-medium">{eventLabel(event.event_type)}</h3><SeverityBadge severity={eventSeverity(event)} /></div><p className="mt-2 font-mono text-[var(--text-xs)] text-[var(--text-muted)]">{event.event_id}</p>{explanation && <p className="event-explanation">{explanation}</p>}<dl className="detail-grid">{rows.filter(([, value]) => value !== null && value !== undefined && value !== "").map(([label, value]) => <div className="contents" key={String(label)}><dt>{label}</dt><dd>{String(value)}</dd></div>)}</dl>{Object.keys(event.metadata).length > 0 && <><h4 className="metadata-title">Metadatos observados</h4><pre className="json-block">{JSON.stringify(event.metadata, null, 2)}</pre></>}</aside>; }
